### ISSUE TITLE
Default home app not supported?

### ISSUE THREAD

**Issue by djensenius** [georgo/homebridge-raspberrypi#2]
I get a device is not supported with iOS 11 using the default Home app.

**Comment by georgo** [comment]
Hi, thank you for your feedback. Home app is not supported yet, goal in future is to display at least temperature.

**Comment by georgo** [comment]
Merged by #4

**Comment by georgo** [comment]
Apple Home support was added i **0.0.3** and it's enabled by default. Please refer updated README for more information.

Thanks you for your feedback!
