### ISSUE TITLE
No history?

### ISSUE THREAD

**Issue by djensenius** [georgo/homebridge-raspberrypi#3]
I don't see the history using the Eve app for temperature.

**Comment by georgo** [comment]
Can you please provide more informations? E.g. screenshot from Eve App?
Thanks

**Comment by djensenius** [comment]
![img_0614](https://user-images.githubusercontent.com/782512/44817987-5ba88080-abb5-11e8-86f9-c55c5c1db7bf.png)

**Comment by georgo** [comment]
Thank you. I'm able to replicate issue. I will come back to you, when issue is fixes.

**Comment by georgo** [comment]
Hi, sorry for long time to process this issue. I finally managed to merge changes. Please update plugin to 0.0.2 and you should see history since then.
