### ISSUE TITLE
Only temperature show in HomeKit.

### ISSUE THREAD

**Issue by lostoneast** [georgo/homebridge-raspberrypi#5]
I am use standart config file, but I can see only Raspberry Pi temperature.

**Comment by georgo** [comment]
Hi Ivanko, I'm really sorry, but what you're expecting to see and where ? Can you please provide more information about your issue ?

Thank you,
georgo

**Comment by PierreBrisorgueil** [comment]
hello @georgo  by default install, the plugin only adds one accessory, the temperature, I think @LostOnEast asks you how to add CPU voltage etc ... as it is listed in the description of the repo

**Comment by georgo** [comment]
CPU Voltage is present and is visible only in "Eve" application (https://itunes.apple.com/us/app/eve-for-homekit/id917695792?mt=8).

Plugin creates only one accessory, both metrics are under it.

**Comment by PierreBrisorgueil** [comment]
@georgo okok, I think it was the question, issue can be closed @LostOnEast ?  it will be nice to specify it in the README 

The solution for homekit would be to rework this like a plateform ?

**Comment by georgo** [comment]
@PierreBrisorgueil Probably yes. Let mu put that to README and put that to feature list. I also plan to add more metrics than temperature & voltage.
